install:
  - wget http://gnu.askapache.com/gsl/gsl-latest.tar.gz
  - tar -xvf gsl-latest.tar.gz
  - pushd gsl-2.1 && ./configure --prefix=/usr && make && sudo make install && popd

language: c

compiler: gcc

script: gcc -std=c99 -Wall -I./include main.c src/simulation.c src/chemicalPotential.c src/analysis.c src/eam.c src/parameters.c src/math_functions.c src/point3D.c src/test.c -o test.out -lm -lgsl -lgslcblas -g
